import { fork } from "redux-saga/effects";

import user from "./user";
import googleNearby from "./googleNearby";
import stateCity from "./stateCity";
import init from "./init";
import itemNames from "./itemNames";
import attachment from "./attachment";
import itemBox from "./itemBox";
import suggestedVehicles from "./suggestedVehicles";
import deliveryProfessionals from "./deliveryProfessionals";
import saveVehicle from "./saveVehicle";
import saveProfessional from "./saveProfessional";
import orderPlace from "./orderPlace";
import logout from "./logout";
import recentLocations from "./recentLocations";
import orderListing from "./orderListing";
import orderDetail from "./orderDetail";
import ratingOptions from "./ratingOptions";
import rateDriver from "./rateDriver";
import driverProfile from "./driverProfile";
import notificationListing from "./notificationListing";
import generalSettings from "./generalSettings";
import cmsContent from "./cmsContent";
import notificationStatus from "./notificationStatus";
import updateNotificationToggle from "./updateNotificationToggle";
import orderComplete from "./orderComplete";
import trackOrder from "./trackOrder";
import card from "./card";
import chargeCard from "./chargeCard";
import updateToken from "./updateToken";

export default function* root() {
  yield fork(user);
  yield fork(googleNearby);
  yield fork(stateCity);
  yield fork(init);
  yield fork(itemNames);
  yield fork(attachment);
  yield fork(itemBox);
  yield fork(suggestedVehicles);
  yield fork(deliveryProfessionals);
  yield fork(saveVehicle);
  yield fork(saveProfessional);
  yield fork(ratingOptions);
  yield fork(orderPlace);
  yield fork(logout);
  yield fork(recentLocations);
  yield fork(orderListing);
  yield fork(orderDetail);
  yield fork(rateDriver);
  yield fork(driverProfile);
  yield fork(driverProfile);
  yield fork(notificationListing);
  yield fork(generalSettings);
  yield fork(cmsContent);
  yield fork(notificationStatus);
  yield fork(updateNotificationToggle);
  yield fork(orderComplete);
  yield fork(trackOrder);
  yield fork(card);
  yield fork(chargeCard);
  yield fork(updateToken);
}
