# Uncomment the next line to define a global platform for your project
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
require_relative '../node_modules/react-native/scripts/react_native_pods'
platform :ios, '10.0'

target 'RiteHaulerDriver' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  config = use_native_modules!
  use_react_native!(:path => config["reactNativePath"])

  rn_path = '../node_modules/react-native'
  rn_maps_path = '../node_modules/react-native-maps'

  # See http://facebook.github.io/react-native/docs/integration-with-existing-apps.html#configuring-cocoapods-dependencies
  
  pod 'Yoga', path: "#{rn_path}/ReactCommon/yoga"
  # pod 'React', path: rn_path, subspecs: [
  #   'Core',
  #   'CxxBridge',
  #   'DevSupport',
  #   'RCTActionSheet',
  #   'RCTAnimation',
  #   'RCTGeolocation',
  #   'RCTImage',
  #   'RCTLinkingIOS',
  #   'RCTNetwork',
  #   'RCTSettings',
  #   'RCTText',
  #   'RCTVibration',
  #   'RCTWebSocket',
  # ]

  pod 'React', :path => '../node_modules/react-native/'
  pod 'React-Core', :path => '../node_modules/react-native/'

  # React Native third party dependencies podspecs
  pod 'DoubleConversion', :podspec => "#{rn_path}/third-party-podspecs/DoubleConversion.podspec"
  pod 'glog', :podspec => "#{rn_path}/third-party-podspecs/glog.podspec"
  # If you are using React Native <0.54, you will get the following error:
  # "The name of the given podspec `GLog` doesn't match the expected one `glog`"
  # Use the following line instead:
  #pod 'GLog', :podspec => "#{rn_path}/third-party-podspecs/GLog.podspec"
  
  # pod 'Yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
  pod 'Folly', :podspec => "#{rn_path}/third-party-podspecs/Folly.podspec"

  # react-native-maps dependencies
  pod 'react-native-maps', path: rn_maps_path
  pod 'react-native-google-maps', path: rn_maps_path  # Uncomment this line if you want to support GoogleMaps on iOS
  pod 'GoogleMaps'  # Uncomment this line if you want to support GoogleMaps on iOS
  pod 'Google-Maps-iOS-Utils' # Uncomment this line if you want to support GoogleMaps on iOS

  # firebase dependencies
  pod 'Firebase/Core', '~> 6.5.0'
  pod 'Firebase/Storage', '~> 6.5.0'
  pod 'Firebase/Messaging'

  # pod 'RNFirebase', :path => '../node_modules/react-native-firebase/ios'

  pod 'RNCAsyncStorage', :path => '../node_modules/@react-native-community/async-storage'

  pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'

  pod 'RNReanimated', :path => '../node_modules/react-native-reanimated'

  pod 'react-native-viewpager', :path => '../node_modules/@react-native-community/viewpager'

  pod 'react-native-netinfo', :path => '../node_modules/@react-native-community/netinfo'

  pod 'react-native-geolocation', path: '../node_modules/@react-native-community/geolocation'

  pod 'RNSVG', :path => '../node_modules/react-native-svg'

end

# post_install do |installer|
#   installer.pods_project.targets.each do |target|
#     if target.name == 'react-native-google-maps'
#       target.build_configurations.each do |config|
#         config.build_settings['CLANG_ENABLE_MODULES'] = 'No'
#       end
#     end
#     if target.name == "React"
#       target.remove_from_project
#     end
#     if target.name == "yoga"
#       target.remove_from_project
#     end
#   end
# end

post_install do |installer|
  installer.pods_project.targets.each do |target|
   if target.name == "React"
     target.remove_from_project
   end
  end
 end
 
# post_install do |lib|
#   lib.pods_project.targets.each do |target|
#       target.build_configurations.each do |config|
#           config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '10.0'
#       end
#   end
# end
